CREATE ROLE calc WITH LOGIN NOSUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION PASSWORD '123456'; GRANT calc TO postgres;

CREATE DATABASE calc_db WITH OWNER = calc ENCODING = 'UTF8' CONNECTION LIMIT = -1;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';

CREATE TABLE calculation
(
  id uuid NOT NULL,
  operation TEXT NOT NULL,
  operands TEXT NOT NULL,
  result TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS public.calculation
  OWNER to calc;