# This file is part of the Lambda Seed project.
# It is used by AWS CodePipeline and CodeBuild to build and package the application.
# The Pipeline and CodeBuild projects are defined in the lambda-pod project.
# If you are not using lambda-pod you can safely delete this file.
version: 1

batch:
  fast-fail: true
env:
  parameter-store:
    CACHE_BUCKET: codepipeline-cache-bucket

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm ci --no-audit --prefer-offline

  build:
    commands:
      - echo Building the Serverless application...
      - npm run compile
      - serverless package --stage $STAGE --package package  --region $AWS_REGION

artifacts:
  files:
    - 'package/**'
    - serverless.yml
    - package.json
    - package-lock.json
    - esbuild.config.js
    - buildspec-deploy.yml
    - 'node_modules/**'

cache:
  paths:
    - '/root/.npm/**/*'
    - 'node_modules/**'
